# CloudFormation template for creating a Bottlerocket instance to snapshot
# the data volume with container images pre-cached
AWSTemplateFormatVersion: 2010-09-09
Description: Bottlerocket instance for creating EBS snapshot with vLLM image pre-cached

Parameters:
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: "Bottlerocket AMI ID from SSM Parameter Store"
    # Standard variant - SOCI works without GPU, nvidia drivers not needed for image pull
    Default: /aws/service/bottlerocket/aws-k8s-1.34/x86_64/latest/image_id
  InstanceType:
    Type: String
    Description: "EC2 instance type"
    Default: m5.large
  SnapshotSize:
    Type: Number
    Description: "Size of the data volume in GiB (needs to fit container images)"
    Default: 50

Resources:
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub "ec2.${AWS::URLSuffix}"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
      Policies:
        - PolicyName: ECRAndEC2Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeTags"
                Resource: "*"

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref InstanceRole

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiID
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: !Ref InstanceProfile
        EbsOptimized: true
        UserData:
          Fn::Base64: |
            [settings.host-containers.admin]
            enabled = true
        BlockDeviceMappings:
          # Control volume (OS)
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 4
              VolumeType: gp3
              DeleteOnTermination: true
          # Data volume (container images) - this gets snapshotted
          - DeviceName: /dev/xvdb
            Ebs:
              VolumeSize: !Ref SnapshotSize
              VolumeType: gp3
              Throughput: 500
              Iops: 3000
              DeleteOnTermination: true
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeviceIndex: "0"

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber

Outputs:
  InstanceId:
    Value: !Ref Instance
    Description: Instance ID for SSM commands
